CREATE DATABASE PROJECT_1;
USE PROJECT_1;
CREATE TABLE BOOKS(
BOOK_ID SERIAL PRIMARY KEY,
TITLE VARCHAR(200),
AUTHOR VARCHAR (100),
GENRE VARCHAR(100),
PUBLISHED_YEAR INT,
PRICE NUMERIC (10,2),
STOCK INT

);
CREATE TABLE CUSTOMERS(
CUSTOMERS_ID SERIAL PRIMARY KEY,
NAME VARCHAR (100),
EMAIL VARCHAR (100) UNIQUE,
PHONE INT,
CITY VARCHAR(100),
COUNTRY VARCHAR(100)  
);
CREATE TABLE ORDERS (
ORDER_ID SERIAL PRIMARY KEY,
CUSTOMER_ID INT REFERENCES CUSTOMERS (CUSTOMER_ID),
BOOK_ID INT REFERENCES BOOKS (BOOKS_ID),
ORDER_DATE DATE,
QUANTITY INT,
TOTAL_AMOUNT NUMERIC (10,2) 
);
SHOW VARIABLES LIKE "secure_file_priv";

-- 1 INSERTING DATA IS IMPORTED IN THE TABLS 
SELECT * FROM BOOKS;
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;
-- 2 all book in the fiction genre:
SELECT * FROM BOOKS
WHERE GENRE = 'FICTION';
-- 3 FIND THE BOOKS AFTER 1950 :
SELECT * FROM BOOKS 
WHERE PUBLISHED_YEAR >1950;
-- 4 LIST ALL THE CUSTOMERS FROM THE CANDA 
SELECT * FROM CUSTOMERS
WHERE COUNTRY = 'CANADA';
-- 5 SHOW THE ORDER PLACED IN NOVEMBER 2023
SELECT * FROM ORDERS
WHERE ORDER_DATE BETWEEN '2023-11-01' AND '2023-11-30';
-- 6 RETRIVE THE TOTAL STOCK OF BOOKS:
SELECT SUM(STOCK) AS TOTAL_STOCK FROM BOOKS;
-- 7 FIND THE DEATILS OF MOST EXPENSIVE BOOL:
SELECT * FROM BOOKS ORDER BY PRICE DESC LIMIT 1 ;
-- 8 SHOW ALL CUSTOMERS WHO ORDERED MORE THAN 1 QUANTITY OF A BOOK
SELECT * FROM ORDERS
WHERE QUANTITY > 1 ;
-- 9 RETRIVE ALL OREDER WHERE THE TOTAL AMOUNT EXCEED $20
SELECT * FROM ORDERS
WHERE TOTAL_AMOUNT>20;
-- 10 SHOW ALL GENRE FROM BOOKS
SELECT DISTINCT GENRE FROM BOOKS ; 
-- 11 SHOW THE MINIMUM STOCK
SELECT * FROM BOOKS ORDER BY STOCK LIMIT 1 ;
-- 12 CALCULATE THE TOTAL REVENUE FROM ORDER 
SELECT SUM(TOTAL_AMOUNT)AS REVENUE FROM ORDERS;

-- ADVANCE QUERY --
-- 13 FIND THE TOOTAL NUMBER OF BOOOKS FRO EACH GENRE

SELECT B.GENRE ,SUM(QUANTITY) AS TOTAL_NUMBER_OF_SOLD FROM ORDERS O
JOIN BOOKS B ON O.BOOK_ID = B.BOOK_ID
GROUP BY GENRE ;
-- 14 FIND AVERAGE PRICE OF BOOKS IN THE FANRASY GENRE
SELECT  AVG(PRICE) AS AVERGAE_PRICE
FROM BOOKS
WHERE GENRE = 'FANTASY'
-- 15 LIST OF CUSTOMERS WHO HAVE PLACE ATLEAST TWO ORDERS

-- 16  SELECT CUSTOMER_ID,COUNT(ORDER_ID) AS ORDER_COUNT
-- FROM ORDERS
-- GROUP BY CUSTOMER_ID
-- HAVING COUNT(ORDER_ID)>=2;

SELECT O.CUSTOMER_ID , C.NAME , COUNT(O.ORDER_ID) AS ORDER_COUNT
FROM ORDERS O
JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMERS_ID 
GROUP BY O.CUSTOMER_ID , C.NAME
HAVING COUNT(ORDER_ID) >= 2;

-- 17 FINT MOST FREQUENTLY BUYING BOOK
SELECT O.BOOK_ID , B.TITLE , COUNT(ORDER_ID) AS ORDER_QUANTITY
FROM ORDERS O 
JOIN BOOKS B ON O.BOOK_ID = B.BOOK_ID
GROUP BY BOOK_ID,B.TITLE
ORDER BY ORDER_QUANTITY DESC LIMIT 1;
-- 18 SHOW THE TOP 3 MOST EXPWENSIVE BOOKS OF 'FANTASY GENRE
SELECT * FROM BOOKS 
WHERE GENRE  = 'FANTASY' ORDER BY PRICE DESC LIMIT 5;
-- 19 RETRIVE THE TOTAL QUANTITY OF BOOKS SOLD BY EACH AUTHOR
SELECT B.AUTHOR  ,B.TITLE, SUM(O.QUANTITY) AS TOTAL_BOOK_SOLD
FROM ORDERS O
JOIN BOOKS B ON O.BOOK_ID = B.BOOK_ID
GROUP BY B.AUTHOR,B.TITLE;
-- 20 LIST THE CITIES WHERE CUSTOMERS WHO SPENT OVER $30 ARE LOCATED
SELECT DISTINCT C.CITY, O.TOTAL_AMOUNT FROM ORDERS O 
JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMERS_ID
WHERE O.TOTAL_AMOUNT >30; 
-- 21 FIND THE CUSTOMER WHO SPENT THE MOST ON ORDERS
SELECT C.CUSTOMERS_ID , C.NAME , SUM(O.TOTAL_AMOUNT) AS TOTAL_SPEND FROM ORDERS O
JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMERS_ID
GROUP BY C.CUSTOMERS_ID,C.NAME
ORDER BY TOTAL_SPEND DESC LIMIT 1;
-- 22 CALCULATE THE STOCK REMANING AFTER FULFILLING ALL ORDERS
 SELECT B.BOOK_ID,B.TITLE,B.STOCK ,COALESCE(SUM(O.QUANTITY),0) AS ORDER_QUANTITY,
 B.STOCK-COALESCE(SUM(O.QUANTITY),0) AS REMAINING_QUANTITY
 FROM BOOKS B
 LEFT JOIN ORDERS O ON B.BOOK_ID = O.BOOK_ID
 GROUP BY B.BOOK_ID ORDER BY B.BOOK_ID;
 
 

 























